### ISSUE TITLE
Include some kind of streaming data representation

### ISSUE THREAD

**Issue by snoyberg** [haskell-foundation/foundation#119]
Given that Foundation is (IMO rightfully) avoiding lazy I/O, it would be good to include a replacement for it out-of-the-box, and that brings up the question of streaming data libraries. Obviously we won't depend on existing libraries given Foundation's ban on them, but the solution here _should_ be based on previous experience. I would broadly summarize the options into the following:
- A coroutine-based approach (like is used by conduit, enumerator, iteratee, pipes, etc)
- A manual `IO`-centric approach like io-streams
- A listt-done-right approach, with two suboptions here:
  - A straightforward implementation along the lines of https://hackage.haskell.org/package/list-transformer-1.0.1/docs/List-Transformer.html
  - An optimized implementation leveraging stream fusion like http://www.yesodweb.com/blog/2016/02/first-class-stream-fusion

Another question is whether we should abstract away from a concrete representation of the streaming primitives using typeclasses (like `MonadPlus`) and leave the choice to the user. Personally, the trade-offs I see are:
- Coroutine libraries are the most flexible, scale to larger problem domains nicely, but are less efficient (higher temporary allocations and CPU usage) and have more cognitive overhead. The performance issue isn't typically a problem in I/O operations though, where the I/O itself vastly dominates the runtime.
- Stream fusion is a great choice if we're preferring performance over all else, but it does have limitations for composability. Still, relative to existing lazy data structures, it's not really missing too much.
- While list-transformer is great for simplicity, I don't think it gives enough benefit over stream fusion to be worth the performance hit (though this is definitely up to debate).
- I don't have strong opinions on an io-streams like approach, and due to relative lack of experience with it I don't want to share half-baked opinions.

I can provide some examples of what I think a good trade-off coroutine based approach would look like based on the past few years of conduit and pipes both being around, but as we've experienced in the past, there's not likely to be a common ground that makes everyone happy. That itself agitates towards making one of the listt-style approaches the standard in Foundation.

**Comment by ndmitchell** [comment]
FWIW, I think foundations absolute ban on third party libraries is a mistake. For things like hashable and conduit I would argue the advantages to being able to integrate downstream outweigh the disadvantages of dependencies. I've shared this opinion with Vincent before in person.

In addition, I spent a few frustrating hours last week trying to make an http server response from wai just forward to an http request I was making to another server. I appreciate you deliberately separated wai and conduit, but when I tried putting them back together I basically went on a random walk until the types told me I had got it right.

**Comment by vincenthz** [comment]
@ndmitchell: I'm not sure how this relate to the streaming discussion @snoyberg start here.

1) maybe it would be a good idea to start another discussion about third party libraries and what we can do to alleviate the problem. It maybe worthwhile to see if we can depends on some library temporarily (behind a cabal flag) until we get all the piece in place. Having no dependencies is a obvious pain, but ultimately I think this will be rewarding. (hashable is a good example of this, it's been gathering dust since both maintainers have moved on :( ).

2) Maybe a good idea to illustrate which point you're making with wai and conduit; (also If there a link with foundation not using any 3rd party library). I think reading a bit between lines are you saying that it's better not too have too many abstractions on top of each other ?

**Comment by ndmitchell** [comment]
@vincenthz - my comment makes perfect sense if you are privy to the conversions I've had individually with both you and @snoyberg - and thus probably makes sense to no one but me... I've pushed the hashable discussion into #121.

For streaming, I think foundation providing some streaming support is clearly desirable. Haskell is in the position of having two streaming ecosystems (conduit and pipes), both of which are pretty good, well tested, well thought out and in regular use. I don't think there's much value in reinventing wheels unless you can think of a way to do it better. If @snoyberg thinks he can, then great, but otherwise it seems like more than you might want to bite off.

The route I suspect @snoyberg is pushing you towards (which makes sense given your stated goals) is similar to what he did for Wai, when he took conduit out of Wai, and instead added the minimum callback-based streaming to integrate with any streaming library. That sounds like a nice goal - compatible with all, based around the primitives etc. What I'm saying is that, with my user hat on, it caused me a couple of frustrating hours last week. I wanted to compose two things from the @snoyberg empire, and they no longer fit together. Of course, there are wrapper packages that help, but they have confusingly similar imports, and confusingly similar but different types, and I still couldn't plug them together nicely - my brain just got into a big tangle and I solved it by copy-paste and guesswork. If Foundation comes up with its own streaming primitives it will probably increase the number of instances of that confusion.

**Comment by vincenthz** [comment]
FWIW, I'ld rather not reinvent the streaming myself ! I don't want to be constraint by anything existing, but if something already solve the problem well and incorporate well in foundation, then that's fine ! In any case, I'm happy to stay on the back sit (and help) and have people that already have more experience with streaming than me, help drives this.

Related to wai and conduit, I can't help but **hope** that's one thing that foundation will solve (not necessary for wai and conduit but generally), being a more consistent platform than a thousand packages scaffolding on each other (thousand cuts).

**Comment by ndmitchell** [comment]
From what I've seen, I think either pipes or conduits would both incorporate well into foundation - none of the directions you've gone in really say much about the streaming story. (That is in contrast to things like the container packages, which won't gel as nicely.)

Agreed about the general goal. Do remember that kind `*` translations (text, bytestring, string etc) are pretty easy. Given the conduits/pipes are streaming chunks of things in a monad with producers and consumers, it becomes about a million times harder. That said, there were plenty of String vs Text vs ByteString things just in trying to merge the two libraries I was using...

**Comment by snoyberg** [comment]
I've got two concerns with going with conduit or pipes:

1. The previously stated one: it adds a dependency, when Foundation is trying to avoid that. I understand your stance on this @ndmitchell, and is something I raised with @vincenthz initially as potentially making Foundation too radical. But I also understand the reasons for doing it. I'm going to sit on the sidelines for now on this point.
2. We've seen in the community that conduit vs pipes (vs enumerator vs iteratee vs io-streams) is a contentious issue, and none of these choices seems likely to make everyone happy. Personally, I'd obviously be fine with conduit being the One True Solution. But using conduit in common libraries has led to enough friction in the past that I gutted it from http-client and wai. I fully agree with you Neil that this makes the libraries more cumbersome and less useful. But it provided for more shared code across the ecosystem, which is what pushed me in that direction.

Foundation is taking plenty of opinionated steps. We can decide that a streaming layer is yet another one of those. Or we can decide that it's not worth being opinionated and use a lower-level interface which is less useful but fully compatible with lots of other nicer interfaces. Or we could decide that this is a can of worms not worth opening and just close this issue as WONTDO.

**Comment by ndmitchell** [comment]
@snoyberg - a question directly for you - if you were the one who was designing and implementing the streaming solution in foundation would you end up with exactly the same thing you did in conduit?

**Comment by snoyberg** [comment]
If I was doing it from scratch without backwards compatibility concerns, I'd probably fix some warts in conduit. I'd have to test these ideas out to say if they are actually worth it, but potential changes:

* Remove finalizers entirely. They're good for providing some assurances, but in practice don't make much of a difference often, and add significant complexity. They are also (I believe) the only thing which prevents the internal `Pipe` type providing a proper identity function.
* Probably choose different operators (`.|` and `.>` seem to make people more happy). The current selection is historical from the move from enumerator, and causes more confusion than anything.
* Far less emphasis on the `$$` operator, and instead recommend an explicit `runConduit`, e.g. replace `sourceFile src $$ sinkFile dst` with `runConduit $ sourceFile src .| sinkFile dst`
* The type synonyms can cause problems with impredicative types that get solved in weird ways. Perhaps get rid of them entirely, and instead just express everything in terms of `data Conduit i o m r`. So instead of `sourceFile :: Producer o ByteString` we'd have `sourceFile :: Conduit i ByteString m ()`.

I'm not convinced of any of these, but these are the ideas I've toyed with.

**Comment by vincenthz** [comment]
I'm no conduit expert, but I think 2 and particularly 3 would be nice indeed. I've always been quite confused by `$$`, I'ld much rather have an explicit word like `runConduit`

**Comment by snoyberg** [comment]
On the `$$` front, forgot to mention: it can unfortunately lead to degraded performance, but perhaps that could be worked around with a rewrite rule.

**Comment by mitchellwrosen** [comment]
Another rather lightweight library that hasn't been mentioned here: [`streaming`](https://hackage.haskell.org/package/streaming)

**Comment by meteficha** [comment]
Just found this issue while tracking the history of `Foundation.Conduit`. I can see that some conduit code was copy pasted here. It seems that conduit was the chosen one after all.

My question is: what's the plan going forward? Is conduit going to depend on foundation and resourcet be a transitional package?

**Comment by snoyberg** [comment]
I don't have a plan for it, I briefly discussed it on Twitter:

https://twitter.com/snoyberg/status/817768333168836609

**Comment by vincenthz** [comment]
I think we can close this for now.

In term of @meteficha (welcome back !) question, this is up to @snoyberg to decide on this, and as he probably know, I'm happy to discuss this whenever, to see what's the forces at play (compat, dependency, etc..). Also foundation being so new, it makes sense to be conservative in this kind of change for now.

Also in term of other frameworks, I had an interesting discussion that `streaming` could better handle linear types than conduit, so it would be a "better default choice". that's an interesting argument provided we do get linear types at some point.

That being said, this is not an exclusive or case, potentially, while conduit is there in foundation and will be supported going forward, we could in the future add another streaming framework along and make them live together without a problem (provided good reasons to do that)

**Comment by meteficha** [comment]
Sounds reasonable! And thanks! :)
