### ISSUE TITLE
What is the best way to deal with stdin and stdout ?

### ISSUE THREAD

**Issue by Josef-Vonasek** [haskell-foundation/foundation#234]
In classic Prelude I used to use interact whenever I could : 

```
main = interact $ unlines . map encodeToString . map myfunc . map decodeFromStrig . lines
```

In Foundation there is no interact nor unlines and lines. Should I write these functions myself or is there better way to deal with stdin and stdout? Is Parser meant for this?

**Comment by vincenthz** [comment]
I would like to avoid all sort of lazy things, so here my thinking would be to have this workflow through conduit (completely untested and not even compiled check):

```haskell
import Foundation
import Foundation.Conduit
import Foundation.Conduit.Textual
import Foundation.String (Encoding(..))

main = runConduit $ sourceHandle stdin .| fromBytes UTF8 .| lines .| something myfunc .| toBytes UTF8 .|. sinkHandle stdout
```

**Comment by ndmitchell** [comment]
`interact` was very sensitive to buffering and laziness, so it's never something I'd encourage. @vincenthz - in the above do you imagine `lines` is the `String` one or the conduit one?

**Comment by vincenthz** [comment]
It would be conduit's `lines` one. In term of buffering I want to get rid of all the handle buffering when we move to foundation's `Handle`, which in essence would be the same as having `NoBuffering` on handle with no way to change.

I expect all the buffering could be better done through conduit in `sourceHandle` and `sinkHandle`, or possibly re-add some conduit like combinator to specify the sometimes useful `LineBuffering` and/or giving the ability to buffer differently.

**Comment by vincenthz** [comment]
@ndmitchell for clarity, "never something I'd encourage" apply to base's interact right ? or to the rewrite using conduit ?

**Comment by ndmitchell** [comment]
@vincenthz I'd never use interact. I've used it before (it was the only IO thing in my first Haskell course) and it's not something that should be repeated. 

I worry about no buffering - given a conduit the buffer strategy is obvious and if it's easy to screw up people will. I guess as long as handle to conduit buffers and does page sized reads all will be good.

**Comment by vincenthz** [comment]
The buffering in Haskell (and in C with fopen/fread/fwrite family) is only to make something that shouldn't be done, faster; namely pretending that you're getting bytes/chars from the system at the speed the API want (e.g. hGetChar) instead of the speed of the underlaying device ("block size" for disk for example).

We have the luxury to make a much nicer api that was ever possible in C, through conduit (or people can use their things on the lowlevel IO api which are less magic)

So conduit will always chunk the read (at block size when needed), to pull data from a handle, and the rest of the conduit pipeline will have to deal with a chunk. https://github.com/haskell-foundation/foundation/blob/master/Foundation/Conduit.hs#L54

On the write side it's slightly more complicated because a valid strategy could be to push to the system the chunks as they are (very likely smaller than block size) which is what is currently implemented https://github.com/haskell-foundation/foundation/blob/master/Foundation/Conduit.hs#L73 , but we could very well have a blockSizeReconstruction step just before the sinkHandle which would concat multiple chunks up to block size before calling hPut.

This overall make us move from a stateful api (base's `Handle` which have a buffering mode and a mutable memory associated) to a "stateless" api where you're buffering at the pipeline level.

adding @snoyberg to the discussion to keep me honest about what we can/can't do :)

**Comment by vincenthz** [comment]
@Josef-Vonasek the function to deal with conduit/lines and stdin/stdout are now in master

I've made an example program that process lines and capitalize all 'a' at: https://github.com/haskell-foundation/foundation/blob/master/programs/InputOutputLines.hs
