### ISSUE TITLE
Convert foundation String to ByteString

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#262]
There are no helpful functions for converting a foundation string to a byte string. I suspect you need two code paths - one to copy the string, and one to convert a `Final` into a `ForeignPtr`.

**Comment by vincenthz** [comment]
`toBytes UTF8` ?

**Comment by ndmitchell** [comment]
Yes, but how do you then get from a `UArray` to a `ByteString`?

**Comment by vincenthz** [comment]
ah, this one is part of `foundation-edge` https://github.com/haskell-foundation/foundation-edge/blob/master/Foundation/Compat/ByteString.hs#L27

This is probably not what you want since this convert to list and back to bytestring; adding a more efficient implementation is probably not to hard, and would indeed convert a final to a foreignPtr. as to the `copy` one, one could use the previous method and use `ByteString.copy` ?

**Comment by ndmitchell** [comment]
Ah, I checked foundation-edge on Hackage which lacks that method - I'm happy with that if you want to close this issue.

**Comment by vincenthz** [comment]
sorry, completely forgot to release `foundation-edge`. there's now a 0.0.2
