### ISSUE TITLE
Drop support for legacy compilers (ghc 7.4 and 7.6)

### ISSUE THREAD

**Issue by NicolasDP** [haskell-foundation/foundation#278]
Are you against? 👎 
Are you for? 👍

**Comment by vincenthz** [comment]
In a perfect infinite time world, it would be nice to keep the support going, but as another "it just doesn't work on 7.6, because bla not supported / difference in type system / etc" hits my latest PR (and many other PRs before), I think it would be clearly better to concentrate on the latest compilers so we can provide feature faster
