### ISSUE TITLE
Add copyFromPtr

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#284]
```
newFromPtr :: Count -> Ptr ty -> prim (UArray ty)
```

Which copies the array from a Ptr, into either a pinned or unpinned lump as appropriate. I couldn't see any way to do that equally efficiently outside the library.

Also possible to do `copyFromPtr` as well?

**Comment by vincenthz** [comment]
I'm not sure I see the difference. would `newFromPtr` and `copyFromPtr` not work exactly the same ?

**Comment by ndmitchell** [comment]
Sorry, too much C yesterday- in a language without mutation they are the same.

**Comment by vincenthz** [comment]
well, I could see a "thawFromPtr" like operation which create a MUArray, although at this point, it's probably better to resort to new+memcpy

**Comment by vincenthz** [comment]
so there's now copyFromPtr which copy to an existing mutable uarray, and freezeFromPtr which create a new uarray from the data pointed at Ptr.

**Comment by vincenthz** [comment]
@ndmitchell I'm thinking of changing `copyToPtr` to take a MutableUArray, and rename the current `copyToPtr` be `thawToPtr`; this way the api would look a bit more consistent, thoughts ?

**Comment by ndmitchell** [comment]
Agreed, that sounds consistent. I am not used to working with freeze and thaw names, so they look a bit alien to me, but it all seems sensible when I compare to vector.

That said, maybe freeze/thaw are weird in vector too? They all seem like copies, and you are just putting the change in mutability as a word instead of copy? copy, copyToMArray, copyToArray, copyToPtr all look better to my eye. The fact Ptr is mutable is a weird detail to focus on given I might not ever mutate it. I would only use freeze/thaw for the unsafe zero copy variants, which don't involve a copy.

**Comment by vincenthz** [comment]
The terminology is not the best and mixing lots of concept. I can't really think of anything better though.

`unsafeThaw` and `unsafeFreeze` are the only one that make really sense (naming wise). thaw and freeze for that matter don't actually thaw or freeze data, they create a new data that is considered `mutable and populated by the src immutable data` or `immutable and populated by the src mutable data`.

Maybe for the freezing type of operation which involve a new block/uarray, renaming everything to be `create...` instead of `freeze...` could make sense.

for Ptr it make sense to consider (pessimistically) as mutable data, whether or not you're going to mutate it. It's only after putting a type on top (ByteString, ..) and that you control the API to this type, that you'll have a choice.

**Comment by ndmitchell** [comment]
Agreed that `freeze` and `thaw` only make sense in very limited cases, and only for the `unsafe` variants. For `copyFromPtr`, I think `createFromPtr` works well. However in the reverse it should be `copyToPtr`, not `createToPtr` since you skip the alloc. I imagine you want `copyToMutable` and `createToMutable` which does the allocation as well (with the caveat that `createToMutable` is a terrible name).
