### ISSUE TITLE
Lines should either ignore '\r' or document it and have linesWithR

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#331]
Since foundation does binary IO by default (a sensible choice), often `lines` will do the wrong thing unless you `filter (/= '\r')` first. Perhaps provide `linesWithR` or something that does normal lines plus filters out `\r`?

**Comment by vincenthz** [comment]
using filter after the fact is probably much less efficient. I would definitely prefer a lines function that cut '\r\n' or/and '\n', although as a workaround for the non existant function we could lines + revDropWhile (== '\r'), (which obviously doesn't exist either, since apparently I do that :))

**Comment by ndmitchell** [comment]
Thinking further, people rarely (if ever) want lines which leaves trailing `\r` at the end of lines, so suggest doing this in the standard `lines` function - otherwise the standard Windows compat bug will be changing all instances of `lines` to `linesWithCR`.

**Comment by vincenthz** [comment]
I gave this more thoughts too and this is not straightforward:

* prelude lines only split on '\n' (i.e. unix mode)
* the textual handle mode for windows is putting everything in unix mode (at a cost of rewriting).

Since everything in foundation is going to binary that open a can of worm related to this:

1. provide a binary translation conduit that is only active on windows otherwise would just let things through on unix
2. make conduit lines system dependant (split on LF only on unix, and CRLF on windows)
3. make it a sourceHandleTextual derivative of sourceHandle which would do all possible rewriting (UTF16 -> UTF8, CRLF -> LF, ...) in one place. This could work either in autodetect mode (which UTF, which linefeed mode) or this could also expect specific mode (and error if not)

1. easy to forget to put the windows only rewriting when working on unix system, cost of rewriting "twice" when doing lines after that
2. more efficient, but if you process your lines yourself from multi lines (e.g. a parser), you need to keep this implementation detail in mind
3. less efficient on windows only, but most flexible and reduce the number of user level impact

**Comment by vincenthz** [comment]
Also I'm tempted to expose String's `lines` with a non-optional parameter for the mode, e.g.:

```haskell
data LineMode = CRLF | LF | AutoDetect | SystemDependent
lines :: LineMode -> String -> [String]
```

**Comment by ndmitchell** [comment]
A lot of developers test only on one platform. I think it's a reasonable goal that whatever we do should work for as many developers as possible, without requiring them to take a "make it work on Windows" special case patch.

I think textual file handles is an awful idea, too many mistakes are made this way. At the same time, I think `lines` should always strip `\r`. That's distinct from `CRLF` - you want to match the pattern of an option `\r` followed by a required `\n` - not `\r\n`. What would your LineMode do?

* Does `CRLF` require `\r\n` line endings? I hope not, since no one ever wants that.
* `LF` works perfectly most of the time, until it doesn't. Then as a Windows user I have to go patch everyone using `LF` to use the right thing, and get broken programs until I do.
* `AutoDetect` is terrible. You can't get this right - whatever heuristic will break randomly.
* `SystemDependent` confuses OS with file format - they just don't match. I use Windows files on Linux, and Linux files on Windows. With things like VM's and shared drives it's even less accurate.

What's the reason against binary handles, and `lines` which matches optional `\r` followed by `\n`?
