### ISSUE TITLE
Revert or review my change

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#419]
Apologies, I pushed directly to the repo, because apparently I have permissions to do that (can they please be removed).

Changes are:

* e1ebcc4a488279b4e9bfbac1a0cc0db452a566d6 - extract the touch functions on Block/MutableBlock. As requested in #417.
* 5866b105c3930b8efddfa38506399efce4d8ff6e - rewrite `mutableWithPtr` in terms of `withPtr` and `unsafeFreeze`, which gives the same operations, but with less direct unsafety.

**Comment by ndmitchell** [comment]
You might also wish to consider turning on branch protections, to stop anyone merging to master: https://help.github.com/articles/configuring-protected-branches/

**Comment by vincenthz** [comment]
I think the commits are fine, no need for a revert.

That being said I'm wondering if there's any difference between unsafeFreezeByteArray# and unsafeCoerce#. I've looked at the former and it seems like a generic no-op assignment, so that should be fine assuring that the `MutableByteArray#` cannot be GC'ed since we're only going to touch the `ByteArray#`. To me it looks like `unsafeCoerce#` in this specific case would look safer, as there's no possible ambiguity now or in the future, about what the primitive is doing.

In term of the operational bits:

* writable permissions: I think it's useful for more than just the core contributors to be able to push to repo; it's obviously not the recommended workflow, but I think it's useful to have more flexibility in some cases. One of the few things is that allow to push to a branch in the repo which can be shared between contributors (when adding things on top of someone else branch), or to push documentation updates using github editor directly without having to create a personal repo.
* pushing to master: protected master make sense, however I'm still pushing to master for making release (and when doing some documentation updates). So I need to workout a different way to do that before that happen (suggestions welcome)
* revert commits are not a problem, for casual mistakes like pushing to master instead of a branch. unless that happens very often, I'm more tempted to just shrug it off than do anything about it :)

**Comment by ndmitchell** [comment]
I suggest you take me off the contributors/permissions list - my text editor of choice makes it disturbingly easy to make this mistake again and again. I'm always happy to PR from a personal repo. 

The rules around unsafeCoerce are somewhat subtle - e.g. Coerce between double and word64 is illegal. I prefer the unsafeFreeze - although suspect it shouldn't really be in the Prim monad to indicate it really is a no op and is more a pointer representational change than something on the array itself. Something to raise with GHC HQ?

**Comment by vincenthz** [comment]
yes, I'm not suggesting `unsafeCoerce#` in the general case but just this specific case (mba# to ba#) seems better. alternatively being able to byteArrayContent# on a mba# would solve this; it would be nice to clarify stuff out with better primtiives, but we'll still be stuck with ghc 7.10 and highers primitives for a while

**Comment by ndmitchell** [comment]
I know operationally `unsafeCoerce` in this specific case is probably the same, but still, it makes me very nervous. Even if the primitives only arrive in 8.4, having them at all makes it feasible to mock the current primitives back to old versions (e.g. with unsafeCoerce) in a way that worries me much less.

**Comment by vincenthz** [comment]
although just to be clear I didn't suggest to move to `unsafeCoerce#`, just that it seemed safer in term of "clearer semantic" (which is obviously arguable when it come to unsafeCoerce#) than `unsafeFreezeByteArray#`.

**Comment by ndmitchell** [comment]
Ah, sorry, I thought you were actually suggesting it! Agreed, the semantics are way nicer - unsafeFreezeByteArray# should not be stateful if it isn't really.
