### ISSUE TITLE
Remove MIN_VERSION_base(4,7,0)

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#450]
That matches GHC 7.8, and given foundation only supports very new things, that compat can be removed. That in turn allows things like `compatAndI#` to be removed as it would always be `andI#`.

**Comment by vincenthz** [comment]
I don't mind too much if it goes away, but I'm not going to actively remove it either now.

**Comment by CaptJakk** [comment]
Looks like this issue is marked as help wanted. I would love to help, just want to know a little bit more about the issue. Here's what I understand the issue to be:

You want to deprecate support for 7.8 and before. Since for other unspecified reasons it is already unsupported by Foundation, we can remove various compatibility cruft that only exists to attempt to support versions of GHC before 7.8. Is this correct?

**Comment by vincenthz** [comment]
only the current latest 3 major versions of ghc are supported at any given time; my comment was about me lazily deleting old compat, instead of deleting it actively
